spring.application.name=winter-olympics

spring.datasource.url=jdbc:postgresql://localhost:5434/winter_olympics
spring.datasource.username=olympics
spring.datasource.password=olympics

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
